--------------------------------------------------------- 
--  This code is generated by Terasic System Builder 
--------------------------------------------------------- 

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity mips_32 is
  port
    (
      ------------ CLOCK ------------ 
      CLOCK_50 : in std_logic;

      ------------ KEY ------------ 
      KEY : in std_logic_vector(3 downto 0);

      ------------ SW ------------ 
      SW : in std_logic_vector(9 downto 0);

      ------------ LED ------------ 
      LEDR : out std_logic_vector(9 downto 0);

      ------------ Seg7 ------------ 
      HEX0 : out std_logic_vector(6 downto 0);
      HEX1 : out std_logic_vector(6 downto 0);
      HEX2 : out std_logic_vector(6 downto 0);
      HEX3 : out std_logic_vector(6 downto 0);
      HEX4 : out std_logic_vector(6 downto 0);
      HEX5 : out std_logic_vector(6 downto 0);

      ------------ HPS ------------ 
      -- HPS_CONV_USB_N    : inout std_logic;
      HPS_DDR3_ADDR    : out   std_logic_vector(14 downto 0);
      HPS_DDR3_BA      : out   std_logic_vector(2 downto 0);
      HPS_DDR3_CAS_N   : out   std_logic;
      HPS_DDR3_CKE     : out   std_logic;
      HPS_DDR3_CK_N    : out   std_logic;
      HPS_DDR3_CK_P    : out   std_logic;
      HPS_DDR3_CS_N    : out   std_logic;
      HPS_DDR3_DM      : out   std_logic_vector(3 downto 0);
      HPS_DDR3_DQ      : inout std_logic_vector(31 downto 0);
      HPS_DDR3_DQS_N   : inout std_logic_vector(3 downto 0);
      HPS_DDR3_DQS_P   : inout std_logic_vector(3 downto 0);
      HPS_DDR3_ODT     : out   std_logic;
      HPS_DDR3_RAS_N   : out   std_logic;
      HPS_DDR3_RESET_N : out   std_logic;
      HPS_DDR3_RZQ     : in    std_logic;
      HPS_DDR3_WE_N    : out   std_logic;
      HPS_ENET_GTX_CLK : out   std_logic;
      HPS_ENET_MDC     : out   std_logic;
      HPS_ENET_MDIO    : inout std_logic;
      HPS_ENET_RX_CLK  : in    std_logic;
      HPS_ENET_RX_DATA : in    std_logic_vector(3 downto 0);
      HPS_ENET_RX_DV   : in    std_logic;
      HPS_ENET_TX_DATA : out   std_logic_vector(3 downto 0);
      HPS_ENET_TX_EN   : out   std_logic;
      HPS_SD_CLK       : out   std_logic;
      HPS_SD_CMD       : inout std_logic;
      HPS_SD_DATA      : inout std_logic_vector(3 downto 0);
      HPS_UART_RX      : in    std_logic;
      HPS_UART_TX      : out   std_logic;
      HPS_USB_CLKOUT   : in    std_logic;
      HPS_USB_DATA     : inout std_logic_vector(7 downto 0);
      HPS_USB_DIR      : in    std_logic;
      HPS_USB_NXT      : in    std_logic;
      HPS_USB_STP      : out   std_logic
      );
end entity;

--------------------------------------------------------- 
--  Structural coding 
--------------------------------------------------------- 

architecture rtl of mips_32 is

  constant pc_offset : std_logic_vector (31 downto 0) := x"00000004";

  signal imem_readdata : std_logic_vector(31 downto 0);

  -- Data Memory Interface (Read/Write)
  signal dmem_address  : std_logic_vector(31 downto 0);
  signal dmem_write    : std_logic;
  -- signal dmem_writedata : std_logic_vector(31 downto 0);
  signal dmem_readdata : std_logic_vector(31 downto 0);
  signal dmem_byteen   : std_logic_vector(3 downto 0);

  signal pc_en                : std_logic;
  signal next_pc              : std_logic_vector(31 downto 0);
  signal current_pc           : std_logic_vector(31 downto 0);
  signal jmp_pc               : std_logic_vector(31 downto 0);
  signal reg_dst              : std_logic;
  signal alu_src              : std_logic;
  signal mem_2_reg            : std_logic;
  signal reg_write            : std_logic;
  signal mem_read             : std_logic;
  -- signal mem_write            : std_logic;
  signal branch               : std_logic;
  signal alu_op               : std_logic_vector(1 downto 0);
  signal w_addr_i             : std_logic_vector(4 downto 0);
  signal w_data_i             : std_logic_vector(31 downto 0);
  -- signal w_en_i    : std_logic;
  signal r1_data_o            : std_logic_vector(31 downto 0);
  signal r2_data_o            : std_logic_vector(31 downto 0);
  signal alu_control_signal   : std_logic_vector(3 downto 0);
  signal data_from_mux_to_alu : std_logic_vector(31 downto 0);
  signal alu_zero             : std_logic;
  signal shifted_2            : std_logic_vector(31 downto 0);
  signal normal_next_pc       : std_logic_vector(31 downto 0);
  signal jmp_added            : std_logic_vector(31 downto 0);

  -- Intermediate control signals to prevent accidental writes
  signal ctrl_reg_write : std_logic;
  signal ctrl_mem_write : std_logic_vector(3 downto 0);
  signal pc_src         : std_logic;

  signal fifo_0              : std_logic_vector(31 downto 0);
  signal fifo_1              : std_logic_vector(31 downto 0);
  signal fifo_2              : std_logic_vector(31 downto 0);
  signal fifo_valid          : std_logic_vector(2 downto 0);
  signal fifo_update_counter : std_logic_vector(31 downto 0);

  component pc is
    port (
      clk        : in  std_logic;
      reset      : in  std_logic;
      en         : in  std_logic;
      next_pc    : in  std_logic_vector(31 downto 0);
      current_pc : out std_logic_vector(31 downto 0)
      );
  end component;

  component regist is
    port(
      clk       : in  std_logic;
      r1_addr_i : in  std_logic_vector(4 downto 0);
      r2_addr_i : in  std_logic_vector(4 downto 0);
      w_addr_i  : in  std_logic_vector(4 downto 0);
      w_data_i  : in  std_logic_vector(31 downto 0);
      w_en_i    : in  std_logic;
      r1_data_o : out std_logic_vector(31 downto 0);
      r2_data_o : out std_logic_vector(31 downto 0)
      );
  end component;

  component main_ctrl is
    port(
      op_code   : in  std_logic_vector(5 downto 0);
      reg_dst   : out std_logic;
      alu_src   : out std_logic;
      mem_2_reg : out std_logic;
      reg_write : out std_logic;
      mem_read  : out std_logic;
      mem_write : out std_logic_vector(3 downto 0);
      branch    : out std_logic;
      alu_op    : out std_logic_vector(1 downto 0)
      );
  end component;

  component alu_ctrl is
    port(
      alu_op      : in  std_logic_vector(1 downto 0);
      func_code   : in  std_logic_vector(5 downto 0);
      alu_control : out std_logic_vector(3 downto 0)
      );
  end component;

  component alu is
    port(
      in_a        : in  std_logic_vector(31 downto 0);
      in_b        : in  std_logic_vector(31 downto 0);
      alu_control : in  std_logic_vector(3 downto 0);
      zero        : out std_logic;
      alu_out     : out std_logic_vector(31 downto 0)
      );
  end component;

  component mux_register is
    port(
      address_0 : in  std_logic_vector(4 downto 0);
      address_1 : in  std_logic_vector(4 downto 0);
      sel       : in  std_logic;
      output    : out std_logic_vector(4 downto 0)
      );
  end component;

  component mux_alu is
    port(
      data_from_register      : in  std_logic_vector(31 downto 0);
      data_from_sign_extender : in  std_logic_vector(31 downto 0);
      alu_src                 : in  std_logic;
      output                  : out std_logic_vector(31 downto 0)
      );
  end component;

  component mux_32 is
    port(
      input_0 : in  std_logic_vector(31 downto 0);
      input_1 : in  std_logic_vector(31 downto 0);
      sel     : in  std_logic;
      output  : out std_logic_vector(31 downto 0)
      );
  end component;

  component sign_extender is
    port(
      petit    : in  std_logic_vector(15 downto 0);
      extended : out std_logic_vector(31 downto 0)
      );
  end component;

  component shift_2 is
    port(
      input   : in  std_logic_vector(31 downto 0);
      shifted : out std_logic_vector(31 downto 0)
      );
  end component;

  component adder_32 is
    port(
      input_0 : in  std_logic_vector(31 downto 0);
      input_1 : in  std_logic_vector(31 downto 0);
      result  : out std_logic_vector(31 downto 0)
      );
  end component;

  component switcher is
    port(
      clk                 : in  std_logic;
      reset               : in  std_logic;
      button              : in  std_logic;
      manual_en           : in  std_logic;
      ctrl_reg_write      : in  std_logic;
      ctrl_mem_write      : in  std_logic_vector(3 downto 0);
      pc_en               : out std_logic;
      reg_write           : out std_logic;
      dmem_write          : out std_logic;
      fetch_indicator     : out std_logic;
      execute_indicator   : out std_logic;
      writeback_indicator : out std_logic;
      dmem_byteen         : out std_logic_vector(3 downto 0)
      );

  end component;

  component fifo is
    port(
      clk                 : in  std_logic;
      reset               : in  std_logic;
      dmem_write          : in  std_logic;
      r2_data_o           : in  std_logic_vector(31 downto 0);
      fifo_hex0           : out std_logic_vector(6 downto 0);
      fifo_hex1           : out std_logic_vector(6 downto 0);
      fifo_hex2           : out std_logic_vector(6 downto 0);
      fifo_hex3           : out std_logic_vector(6 downto 0);
      fifo_hex4           : out std_logic_vector(6 downto 0);
      fifo_hex5           : out std_logic_vector(6 downto 0);
      fifo_0              : out std_logic_vector(31 downto 0);
      fifo_1              : out std_logic_vector(31 downto 0);
      fifo_2              : out std_logic_vector(31 downto 0);
      fifo_valid          : out std_logic_vector(2 downto 0);
      fifo_update_counter : out std_logic_vector(31 downto 0)
      );
  end component;

-- Blueprint of the Qsys system
  component soc_mips is
    port (
      -- Clock and Reset
      clk_clk       : in std_logic := 'X';
      reset_reset_n : in std_logic := 'X';

      -- HPS DDR3 Memory
      memory_mem_a       : out   std_logic_vector(14 downto 0);
      memory_mem_ba      : out   std_logic_vector(2 downto 0);
      memory_mem_ck      : out   std_logic;
      memory_mem_ck_n    : out   std_logic;
      memory_mem_cke     : out   std_logic;
      memory_mem_cs_n    : out   std_logic;
      memory_mem_ras_n   : out   std_logic;
      memory_mem_cas_n   : out   std_logic;
      memory_mem_we_n    : out   std_logic;
      memory_mem_reset_n : out   std_logic;
      memory_mem_dq      : inout std_logic_vector(31 downto 0) := (others => 'X');
      memory_mem_dqs     : inout std_logic_vector(3 downto 0)  := (others => 'X');
      memory_mem_dqs_n   : inout std_logic_vector(3 downto 0)  := (others => 'X');
      memory_mem_odt     : out   std_logic;
      memory_mem_dm      : out   std_logic_vector(3 downto 0);
      memory_oct_rzqin   : in    std_logic                     := 'X';

      -- HPS Peripherals
      hps_io_hps_io_emac1_inst_TX_CLK : out   std_logic;
      hps_io_hps_io_emac1_inst_TXD0   : out   std_logic;
      hps_io_hps_io_emac1_inst_TXD1   : out   std_logic;
      hps_io_hps_io_emac1_inst_TXD2   : out   std_logic;
      hps_io_hps_io_emac1_inst_TXD3   : out   std_logic;
      hps_io_hps_io_emac1_inst_RXD0   : in    std_logic := 'X';
      hps_io_hps_io_emac1_inst_MDIO   : inout std_logic := 'X';
      hps_io_hps_io_emac1_inst_MDC    : out   std_logic;
      hps_io_hps_io_emac1_inst_RX_CTL : in    std_logic := 'X';
      hps_io_hps_io_emac1_inst_TX_CTL : out   std_logic;
      hps_io_hps_io_emac1_inst_RX_CLK : in    std_logic := 'X';
      hps_io_hps_io_emac1_inst_RXD1   : in    std_logic := 'X';
      hps_io_hps_io_emac1_inst_RXD2   : in    std_logic := 'X';
      hps_io_hps_io_emac1_inst_RXD3   : in    std_logic := 'X';
      hps_io_hps_io_sdio_inst_CMD     : inout std_logic := 'X';
      hps_io_hps_io_sdio_inst_D0      : inout std_logic := 'X';
      hps_io_hps_io_sdio_inst_D1      : inout std_logic := 'X';
      hps_io_hps_io_sdio_inst_CLK     : out   std_logic;
      hps_io_hps_io_sdio_inst_D2      : inout std_logic := 'X';
      hps_io_hps_io_sdio_inst_D3      : inout std_logic := 'X';
      hps_io_hps_io_usb1_inst_D0      : inout std_logic := 'X';
      hps_io_hps_io_usb1_inst_D1      : inout std_logic := 'X';
      hps_io_hps_io_usb1_inst_D2      : inout std_logic := 'X';
      hps_io_hps_io_usb1_inst_D3      : inout std_logic := 'X';
      hps_io_hps_io_usb1_inst_D4      : inout std_logic := 'X';
      hps_io_hps_io_usb1_inst_D5      : inout std_logic := 'X';
      hps_io_hps_io_usb1_inst_D6      : inout std_logic := 'X';
      hps_io_hps_io_usb1_inst_D7      : inout std_logic := 'X';
      hps_io_hps_io_usb1_inst_CLK     : in    std_logic := 'X';
      hps_io_hps_io_usb1_inst_STP     : out   std_logic;
      hps_io_hps_io_usb1_inst_DIR     : in    std_logic := 'X';
      hps_io_hps_io_usb1_inst_NXT     : in    std_logic := 'X';
      hps_io_hps_io_uart0_inst_RX     : in    std_logic := 'X';
      hps_io_hps_io_uart0_inst_TX     : out   std_logic;

      instruction_memory_clk_clk       : in  std_logic                     := 'X';  -- clk
      instruction_memory_rst_reset     : in  std_logic                     := 'X';  -- reset
      instruction_memory_rst_reset_req : in  std_logic                     := 'X';  -- reset_req
      instruction_memory_s2_address    : in  std_logic_vector(9 downto 0)  := (others => 'X');  -- address
      instruction_memory_s2_chipselect : in  std_logic                     := 'X';  -- chipselect
      instruction_memory_s2_clken      : in  std_logic                     := 'X';  -- clken
      instruction_memory_s2_write      : in  std_logic                     := 'X';  -- write
      instruction_memory_s2_readdata   : out std_logic_vector(31 downto 0);  -- readdata
      instruction_memory_s2_writedata  : in  std_logic_vector(31 downto 0) := (others => 'X');  -- writedata
      instruction_memory_s2_byteenable : in  std_logic_vector(3 downto 0)  := (others => 'X');  -- byteenable

      data_memory_clk_clk       : in  std_logic                     := 'X';  -- clk
      data_memory_rst_reset     : in  std_logic                     := 'X';  -- reset
      data_memory_rst_reset_req : in  std_logic                     := 'X';  -- reset_req
      data_memory_s2_address    : in  std_logic_vector(9 downto 0)  := (others => 'X');  -- address
      data_memory_s2_chipselect : in  std_logic                     := 'X';  -- chipselect
      data_memory_s2_clken      : in  std_logic                     := 'X';  -- clken
      data_memory_s2_write      : in  std_logic                     := 'X';  -- write
      data_memory_s2_readdata   : out std_logic_vector(31 downto 0);  -- readdata
      data_memory_s2_writedata  : in  std_logic_vector(31 downto 0) := (others => 'X');  -- writedata
      data_memory_s2_byteenable : in  std_logic_vector(3 downto 0)  := (others => 'X');  -- byteenable

      mips_status_export  : in std_logic_vector(31 downto 0) := (others => 'X');  -- export
      fifo_0_export       : in std_logic_vector(31 downto 0) := (others => '0');  --                 fifo_0.export
      fifo_1_export       : in std_logic_vector(31 downto 0) := (others => '0');  --                 fifo_1.export
      fifo_2_export       : in std_logic_vector(31 downto 0) := (others => '0');  --                 fifo_2.export
      fifo_counter_export : in std_logic_vector(31 downto 0) := (others => '0');  --           fifo_counter.export
      fifo_valid_export   : in std_logic_vector(2 downto 0)  := (others => '0')  --             fifo_valid.export

      );
  end component soc_mips;

begin

  u0 : component soc_mips
    port map (
      -- Clock and Resets 
      clk_clk       => CLOCK_50,
      reset_reset_n => '1',

      -- HPS DDR3 Memory 
      memory_mem_a       => HPS_DDR3_ADDR,
      memory_mem_ba      => HPS_DDR3_BA,
      memory_mem_ck      => HPS_DDR3_CK_P,
      memory_mem_ck_n    => HPS_DDR3_CK_N,
      memory_mem_cke     => HPS_DDR3_CKE,
      memory_mem_cs_n    => HPS_DDR3_CS_N,
      memory_mem_ras_n   => HPS_DDR3_RAS_N,
      memory_mem_cas_n   => HPS_DDR3_CAS_N,
      memory_mem_we_n    => HPS_DDR3_WE_N,
      memory_mem_reset_n => HPS_DDR3_RESET_N,
      memory_mem_dq      => HPS_DDR3_DQ,
      memory_mem_dqs     => HPS_DDR3_DQS_P,
      memory_mem_dqs_n   => HPS_DDR3_DQS_N,
      memory_mem_odt     => HPS_DDR3_ODT,
      memory_mem_dm      => HPS_DDR3_DM,
      memory_oct_rzqin   => HPS_DDR3_RZQ,

      -- HPS Ethernet (EMAC1) 
      hps_io_hps_io_emac1_inst_TX_CLK => HPS_ENET_GTX_CLK,
      hps_io_hps_io_emac1_inst_TXD0   => HPS_ENET_TX_DATA(0),
      hps_io_hps_io_emac1_inst_TXD1   => HPS_ENET_TX_DATA(1),
      hps_io_hps_io_emac1_inst_TXD2   => HPS_ENET_TX_DATA(2),
      hps_io_hps_io_emac1_inst_TXD3   => HPS_ENET_TX_DATA(3),
      hps_io_hps_io_emac1_inst_RXD0   => HPS_ENET_RX_DATA(0),
      hps_io_hps_io_emac1_inst_MDIO   => HPS_ENET_MDIO,
      hps_io_hps_io_emac1_inst_MDC    => HPS_ENET_MDC,
      hps_io_hps_io_emac1_inst_RX_CTL => HPS_ENET_RX_DV,
      hps_io_hps_io_emac1_inst_TX_CTL => HPS_ENET_TX_EN,
      hps_io_hps_io_emac1_inst_RX_CLK => HPS_ENET_RX_CLK,
      hps_io_hps_io_emac1_inst_RXD1   => HPS_ENET_RX_DATA(1),
      hps_io_hps_io_emac1_inst_RXD2   => HPS_ENET_RX_DATA(2),
      hps_io_hps_io_emac1_inst_RXD3   => HPS_ENET_RX_DATA(3),

      -- HPS SD Card 
      hps_io_hps_io_sdio_inst_CMD => HPS_SD_CMD,
      hps_io_hps_io_sdio_inst_CLK => HPS_SD_CLK,
      hps_io_hps_io_sdio_inst_D0  => HPS_SD_DATA(0),
      hps_io_hps_io_sdio_inst_D1  => HPS_SD_DATA(1),
      hps_io_hps_io_sdio_inst_D2  => HPS_SD_DATA(2),
      hps_io_hps_io_sdio_inst_D3  => HPS_SD_DATA(3),

      -- HPS USB 
      hps_io_hps_io_usb1_inst_D0  => HPS_USB_DATA(0),
      hps_io_hps_io_usb1_inst_D1  => HPS_USB_DATA(1),
      hps_io_hps_io_usb1_inst_D2  => HPS_USB_DATA(2),
      hps_io_hps_io_usb1_inst_D3  => HPS_USB_DATA(3),
      hps_io_hps_io_usb1_inst_D4  => HPS_USB_DATA(4),
      hps_io_hps_io_usb1_inst_D5  => HPS_USB_DATA(5),
      hps_io_hps_io_usb1_inst_D6  => HPS_USB_DATA(6),
      hps_io_hps_io_usb1_inst_D7  => HPS_USB_DATA(7),
      hps_io_hps_io_usb1_inst_CLK => HPS_USB_CLKOUT,
      hps_io_hps_io_usb1_inst_STP => HPS_USB_STP,
      hps_io_hps_io_usb1_inst_DIR => HPS_USB_DIR,
      hps_io_hps_io_usb1_inst_NXT => HPS_USB_NXT,

      -- HPS UART 
      hps_io_hps_io_uart0_inst_RX => HPS_UART_RX,
      hps_io_hps_io_uart0_inst_TX => HPS_UART_TX,

      -- Instruction Memory Wiring
      instruction_memory_clk_clk       => CLOCK_50,
      instruction_memory_rst_reset     => not KEY(0),
      instruction_memory_rst_reset_req => '0',  -- Tied to 0
      -- instruction_memory_s2_address    => imem_address,
      instruction_memory_s2_address    => current_pc(11 downto 2),
      instruction_memory_s2_chipselect => '1', instruction_memory_s2_clken => '1',
      instruction_memory_s2_write      => '0',
      instruction_memory_s2_readdata   => imem_readdata,
      instruction_memory_s2_writedata  => (others => '0'),
      instruction_memory_s2_byteenable => "1111",

      -- Data Memory Wiring
      data_memory_clk_clk       => CLOCK_50,
      data_memory_rst_reset     => not KEY(0),
      data_memory_rst_reset_req => '0',  -- Tied to 0
      data_memory_s2_address    => dmem_address(11 downto 2),
      data_memory_s2_chipselect => '1',
      data_memory_s2_clken      => '1',
      data_memory_s2_write      => dmem_write,
      data_memory_s2_readdata   => dmem_readdata,
      data_memory_s2_writedata  => r2_data_o,
      data_memory_s2_byteenable => dmem_byteen,

      fifo_0_export       => fifo_0,
      fifo_1_export       => fifo_1,
      fifo_2_export       => fifo_2,
      fifo_counter_export => fifo_update_counter,
      fifo_valid_export   => fifo_valid,

      -- FPGA Custom Fabric Bridges 
      mips_status_export => current_pc);

  pc_mips : pc
    port map(
      clk        => CLOCK_50,
      reset      => SW(0),
      en         => pc_en,
      next_pc    => next_pc,
      current_pc => current_pc
      );
  register_mips : regist
    port map(
      clk       => CLOCK_50,
      r1_addr_i => imem_readdata(25 downto 21),
      r2_addr_i => imem_readdata(20 downto 16),
      w_addr_i  => w_addr_i,
      w_data_i  => w_data_i,
      w_en_i    => reg_write,
      r1_data_o => r1_data_o(31 downto 0),
      r2_data_o => r2_data_o(31 downto 0)
      );
  main_control : main_ctrl
    port map(
      op_code   => imem_readdata(31 downto 26),
      reg_dst   => reg_dst,
      alu_src   => alu_src,
      mem_2_reg => mem_2_reg,
      reg_write => ctrl_reg_write,
      mem_read  => mem_read,
      mem_write => ctrl_mem_write,
      branch    => branch,
      alu_op    => alu_op(1 downto 0)
      );

  mux_register_inst : mux_register
    port map(
      address_0 => imem_readdata(20 downto 16),
      address_1 => imem_readdata(15 downto 11),
      sel       => reg_dst,
      output    => w_addr_i
      );

  alu_controller : alu_ctrl
    port map(
      alu_op      => alu_op(1 downto 0),
      func_code   => imem_readdata(5 downto 0),
      alu_control => alu_control_signal(3 downto 0)
      );

  sign_32_bit : sign_extender
    port map(
      petit    => imem_readdata(15 downto 0),
      extended => jmp_pc(31 downto 0)
      );

  mux_alu_mips : mux_alu
    port map(
      data_from_register      => r2_data_o(31 downto 0),
      data_from_sign_extender => jmp_pc(31 downto 0),
      alu_src                 => alu_src,
      output                  => data_from_mux_to_alu(31 downto 0)
      );

  alu_mips : alu
    port map(
      in_a        => r1_data_o(31 downto 0),
      in_b        => data_from_mux_to_alu(31 downto 0),
      alu_control => alu_control_signal(3 downto 0),
      zero        => alu_zero,
      alu_out     => dmem_address
      );

  mux_out_data : mux_32
    port map(
      input_0 => dmem_address,
      input_1 => dmem_readdata,
      sel     => mem_2_reg,
      output  => w_data_i
      );

  left_shifter : shift_2
    port map(
      input   => jmp_pc,
      shifted => shifted_2
      );

  adder_branch_target : adder_32
    port map(
      input_0 => normal_next_pc,
      input_1 => shifted_2,
      result  => jmp_added
      );
  adder_pc : adder_32
    port map(
      input_0 => current_pc,
      input_1 => pc_offset,
      result  => normal_next_pc
      );
  mux_jmp_pc : mux_32
    port map(
      input_0 => normal_next_pc,
      input_1 => jmp_added,
      sel     => pc_src,
      output  => next_pc
      );

  pc_src <= alu_zero and branch;

  mips_switcher : switcher
    port map(
      clk            => CLOCK_50,
      reset          => SW(0),
      button         => KEY(0),
      manual_en      => SW(9),
      ctrl_reg_write => ctrl_reg_write,
      ctrl_mem_write => ctrl_mem_write,
      pc_en          => pc_en,
      reg_write      => reg_write,
      dmem_write     => dmem_write,
      fetch_indicator => LEDR(9),
      execute_indicator => LEDR(8),
      writeback_indicator => LEDR(7),
      dmem_byteen    => dmem_byteen
      );

  mips_fifo : fifo
    port map(
      clk                 => CLOCK_50,
      reset               => SW(0),
      dmem_write          => dmem_write,
      r2_data_o           => r2_data_o,
      fifo_hex0           => HEX0,
      fifo_hex1           => HEX1,
      fifo_hex2           => HEX2,
      fifo_hex3           => HEX3,
      fifo_hex4           => HEX4,
      fifo_hex5           => HEX5,
      fifo_0              => fifo_0,
      fifo_1              => fifo_1,
      fifo_2              => fifo_2,
      fifo_valid          => fifo_valid,
      fifo_update_counter => fifo_update_counter
      );

  LEDR(6) <= ctrl_reg_write;
  LEDR(5) <= ctrl_mem_write(0);
  LEDR(4) <= mem_read;
  LEDR(3) <= branch;
  LEDR(2) <= alu_zero;
  LEDR(1) <= alu_src;
  LEDR(0) <= dmem_byteen(0);

end rtl;
