--------------------------------------------------------- 
--  This code is generated by Terasic System Builder 
--------------------------------------------------------- 

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity mips_32 is
  port
    (
      ------------ CLOCK ------------ 
      CLOCK2_50 : in std_logic;
      CLOCK3_50 : in std_logic;
      CLOCK4_50 : in std_logic;
      CLOCK_50  : in std_logic;

      ------------ KEY ------------ 
      KEY : in std_logic_vector(3 downto 0);

      ------------ SW ------------ 
      SW : in std_logic_vector(9 downto 0);

      ------------ LED ------------ 
      LEDR : out std_logic_vector(9 downto 0);

      ------------ Seg7 ------------ 
      HEX0 : out std_logic_vector(6 downto 0);
      HEX1 : out std_logic_vector(6 downto 0);
      HEX2 : out std_logic_vector(6 downto 0);
      HEX3 : out std_logic_vector(6 downto 0);
      HEX4 : out std_logic_vector(6 downto 0);
      HEX5 : out std_logic_vector(6 downto 0);

      ------------ HPS ------------ 
      HPS_CONV_USB_N    : inout std_logic;
      HPS_DDR3_ADDR     : out   std_logic_vector(14 downto 0);
      HPS_DDR3_BA       : out   std_logic_vector(2 downto 0);
      HPS_DDR3_CAS_N    : out   std_logic;
      HPS_DDR3_CKE      : out   std_logic;
      HPS_DDR3_CK_N     : out   std_logic;
      HPS_DDR3_CK_P     : out   std_logic;
      HPS_DDR3_CS_N     : out   std_logic;
      HPS_DDR3_DM       : out   std_logic_vector(3 downto 0);
      HPS_DDR3_DQ       : inout std_logic_vector(31 downto 0);
      HPS_DDR3_DQS_N    : inout std_logic_vector(3 downto 0);
      HPS_DDR3_DQS_P    : inout std_logic_vector(3 downto 0);
      HPS_DDR3_ODT      : out   std_logic;
      HPS_DDR3_RAS_N    : out   std_logic;
      HPS_DDR3_RESET_N  : out   std_logic;
      HPS_DDR3_RZQ      : in    std_logic;
      HPS_DDR3_WE_N     : out   std_logic;
      HPS_ENET_GTX_CLK  : out   std_logic;
      HPS_ENET_INT_N    : inout std_logic;
      HPS_ENET_MDC      : out   std_logic;
      HPS_ENET_MDIO     : inout std_logic;
      HPS_ENET_RX_CLK   : in    std_logic;
      HPS_ENET_RX_DATA  : in    std_logic_vector(3 downto 0);
      HPS_ENET_RX_DV    : in    std_logic;
      HPS_ENET_TX_DATA  : out   std_logic_vector(3 downto 0);
      HPS_ENET_TX_EN    : out   std_logic;
      HPS_FLASH_DATA    : inout std_logic_vector(3 downto 0);
      HPS_FLASH_DCLK    : out   std_logic;
      HPS_FLASH_NCSO    : out   std_logic;
      HPS_GSENSOR_INT   : inout std_logic;
      HPS_I2C1_SCLK     : inout std_logic;
      HPS_I2C1_SDAT     : inout std_logic;
      HPS_I2C2_SCLK     : inout std_logic;
      HPS_I2C2_SDAT     : inout std_logic;
      HPS_I2C_CONTROL   : inout std_logic;
      HPS_KEY           : inout std_logic;
      HPS_LCM_BK        : inout std_logic;
      HPS_LCM_D_C       : inout std_logic;
      HPS_LCM_RST_N     : inout std_logic;
      HPS_LCM_SPIM_CLK  : out   std_logic;
      HPS_LCM_SPIM_MISO : in    std_logic;
      HPS_LCM_SPIM_MOSI : out   std_logic;
      HPS_LCM_SPIM_SS   : out   std_logic;
      HPS_LED           : inout std_logic;
      HPS_LTC_GPIO      : inout std_logic;
      HPS_SD_CLK        : out   std_logic;
      HPS_SD_CMD        : inout std_logic;
      HPS_SD_DATA       : inout std_logic_vector(3 downto 0);
      HPS_SPIM_CLK      : out   std_logic;
      HPS_SPIM_MISO     : in    std_logic;
      HPS_SPIM_MOSI     : out   std_logic;
      HPS_SPIM_SS       : out   std_logic;
      HPS_UART_RX       : in    std_logic;
      HPS_UART_TX       : out   std_logic;
      HPS_USB_CLKOUT    : in    std_logic;
      HPS_USB_DATA      : inout std_logic_vector(7 downto 0);
      HPS_USB_DIR       : in    std_logic;
      HPS_USB_NXT       : in    std_logic;
      HPS_USB_STP       : out   std_logic
      );
end entity;

--------------------------------------------------------- 
--  Structural coding 
--------------------------------------------------------- 

architecture rtl of mips_32 is

  constant pc_offset : std_logic_vector (31 downto 0) := x"00000004";

  signal hps_to_fpga_signal : std_logic_vector(31 downto 0);
-- Instruction Memory Interface (Read-Only)
  signal imem_address       : std_logic_vector(9 downto 0);
  signal imem_readdata      : std_logic_vector(31 downto 0);

  -- Data Memory Interface (Read/Write)
  signal dmem_address  : std_logic_vector(31 downto 0);
  signal dmem_write    : std_logic;
  -- signal dmem_writedata : std_logic_vector(31 downto 0);
  signal dmem_readdata : std_logic_vector(31 downto 0);
  signal dmem_byteen   : std_logic_vector(3 downto 0);

  signal pc_en                : std_logic;
  signal next_pc              : std_logic_vector(31 downto 0);
  signal current_pc           : std_logic_vector(31 downto 0);
  signal jmp_pc               : std_logic_vector(31 downto 0);
  signal reg_dst              : std_logic;
  signal alu_src              : std_logic;
  signal mem_2_reg            : std_logic;
  signal reg_write            : std_logic;
  signal mem_read             : std_logic;
  signal mem_write            : std_logic;
  signal branch               : std_logic;
  signal alu_op               : std_logic_vector(1 downto 0);
  signal w_addr_i             : std_logic_vector(4 downto 0);
  signal w_data_i             : std_logic_vector(31 downto 0);
  -- signal w_en_i    : std_logic;
  signal r1_data_o            : std_logic_vector(31 downto 0);
  signal r2_data_o            : std_logic_vector(31 downto 0);
  signal alu_control_signal   : std_logic_vector(3 downto 0);
  signal data_from_mux_to_alu : std_logic_vector(31 downto 0);
  signal alu_zero             : std_logic;
  signal shifted_2            : std_logic_vector(31 downto 0);
  signal normal_next_pc       : std_logic_vector(31 downto 0);
  signal jmp_added            : std_logic_vector(31 downto 0);
-- state machine signals
  -- State machine signal
  signal cycle_state          : std_logic := '0';

  -- Intermediate control signals to prevent accidental writes
  signal ctrl_reg_write : std_logic;
  signal ctrl_mem_write : std_logic_vector(3 downto 0);
  signal pc_src         : std_logic;

  signal btn_sync_0 : std_logic := '0';
  signal btn_sync_1 : std_logic := '0';
  signal btn_sync_2 : std_logic := '0';
  signal step_pulse : std_logic;


  function bits_2_display7(bits : in std_logic_vector(3 downto 0))
    return std_logic_vector is variable display7 : std_logic_vector(6 downto 0);
  begin
    case bits is
      when "0000" => display7 := "1000000";  -- 0
      when "0001" => display7 := "1111001";  -- 1
      when "0010" => display7 := "0100100";  -- 2
      when "0011" => display7 := "0110000";  -- 3
      when "0100" => display7 := "0011001";  -- 4
      when "0101" => display7 := "0010010";  -- 5
      when "0110" => display7 := "0000010";  -- 6
      when "0111" => display7 := "1111000";  -- 7
      when "1000" => display7 := "0000000";  -- 8
      when "1001" => display7 := "0010000";  -- 9
      when "1010" => display7 := "0001000";  -- A
      when "1011" => display7 := "0000011";  -- b
      when "1100" => display7 := "1000110";  -- C
      when "1101" => display7 := "0100001";  -- d
      when "1110" => display7 := "0000110";  -- E
      when "1111" => display7 := "0001110";  -- F
      when others => display7 := "1111111";  -- blank
    end case;
    return display7;
  end;

  component pc is
    port (
      clk        : in  std_logic;
      reset      : in  std_logic;
      en         : in  std_logic;
      next_pc    : in  std_logic_vector(31 downto 0);
      current_pc : out std_logic_vector(31 downto 0)
      );
  end component;

  component regist is
    port(
      clk       : in  std_logic;
      r1_addr_i : in  std_logic_vector(4 downto 0);
      r2_addr_i : in  std_logic_vector(4 downto 0);
      w_addr_i  : in  std_logic_vector(4 downto 0);
      w_data_i  : in  std_logic_vector(31 downto 0);
      w_en_i    : in  std_logic;
      r1_data_o : out std_logic_vector(31 downto 0);
      r2_data_o : out std_logic_vector(31 downto 0)
      );
  end component;

  component main_ctrl is
    port(
      op_code   : in  std_logic_vector(5 downto 0);
      reg_dst   : out std_logic;
      alu_src   : out std_logic;
      mem_2_reg : out std_logic;
      reg_write : out std_logic;
      mem_read  : out std_logic;
      mem_write : out std_logic_vector(3 downto 0);
      branch    : out std_logic;
      alu_op    : out std_logic_vector(1 downto 0)
      );
  end component;

  component alu_ctrl is
    port(
      alu_op      : in  std_logic_vector(1 downto 0);
      func_code   : in  std_logic_vector(5 downto 0);
      alu_control : out std_logic_vector(3 downto 0)
      );
  end component;

  component alu is
    port(
      in_a        : in  std_logic_vector(31 downto 0);
      in_b        : in  std_logic_vector(31 downto 0);
      alu_control : in  std_logic_vector(3 downto 0);
      zero        : out std_logic;
      alu_out     : out std_logic_vector(31 downto 0)
      );
  end component;

  component mux_register is
    port(
      address_0 : in  std_logic_vector(4 downto 0);
      address_1 : in  std_logic_vector(4 downto 0);
      sel       : in  std_logic;
      output    : out std_logic_vector(4 downto 0)
      );
  end component;

  component mux_alu is
    port(
      data_from_register      : in  std_logic_vector(31 downto 0);
      data_from_sign_extender : in  std_logic_vector(31 downto 0);
      alu_src                 : in  std_logic;
      output                  : out std_logic_vector(31 downto 0)
      );
  end component;

  component mux_32 is
    port(
      input_0 : in  std_logic_vector(31 downto 0);
      input_1 : in  std_logic_vector(31 downto 0);
      sel     : in  std_logic;
      output  : out std_logic_vector(31 downto 0)
      );
  end component;

  component sign_extender is
    port(
      petit    : in  std_logic_vector(15 downto 0);
      extended : out std_logic_vector(31 downto 0)
      );
  end component;

  component shift_2 is
    port(
      input   : in  std_logic_vector(31 downto 0);
      shifted : out std_logic_vector(31 downto 0)
      );
  end component;

  component adder_32 is
    port(
      input_0 : in  std_logic_vector(31 downto 0);
      input_1 : in  std_logic_vector(31 downto 0);
      result  : out std_logic_vector(31 downto 0)
      );
  end component;

  component switcher is
    port(
      clk            : in  std_logic;
      reset          : in  std_logic;
      button         : in  std_logic;
      manual_en      : in  std_logic;
      ctrl_reg_write : in  std_logic;
      ctrl_mem_write : in  std_logic_vector(3 downto 0);
      pc_en          : out std_logic;
      reg_write      : out std_logic;
      dmem_write     : out std_logic;
      dmem_byteen    : out std_logic_vector(3 downto 0)
      );
  end component;


-- Blueprint of the Qsys system
  component soc_mips is
    port (
      -- Clock and Reset
      clk_clk       : in std_logic := 'X';
      reset_reset_n : in std_logic := 'X';

      -- HPS to FPGA Reset
      hps_0_h2f_reset_reset_n : out std_logic;

      -- MPU Events
      hps_0_h2f_mpu_events_eventi     : in  std_logic := 'X';
      hps_0_h2f_mpu_events_evento     : out std_logic;
      hps_0_h2f_mpu_events_standbywfe : out std_logic_vector(1 downto 0);
      hps_0_h2f_mpu_events_standbywfi : out std_logic_vector(1 downto 0);

      -- HPS DDR3 Memory
      memory_mem_a       : out   std_logic_vector(14 downto 0);
      memory_mem_ba      : out   std_logic_vector(2 downto 0);
      memory_mem_ck      : out   std_logic;
      memory_mem_ck_n    : out   std_logic;
      memory_mem_cke     : out   std_logic;
      memory_mem_cs_n    : out   std_logic;
      memory_mem_ras_n   : out   std_logic;
      memory_mem_cas_n   : out   std_logic;
      memory_mem_we_n    : out   std_logic;
      memory_mem_reset_n : out   std_logic;
      memory_mem_dq      : inout std_logic_vector(31 downto 0) := (others => 'X');
      memory_mem_dqs     : inout std_logic_vector(3 downto 0)  := (others => 'X');
      memory_mem_dqs_n   : inout std_logic_vector(3 downto 0)  := (others => 'X');
      memory_mem_odt     : out   std_logic;
      memory_mem_dm      : out   std_logic_vector(3 downto 0);
      memory_oct_rzqin   : in    std_logic                     := 'X';

      -- HPS Peripherals
      hps_io_hps_io_emac1_inst_TX_CLK : out   std_logic;
      hps_io_hps_io_emac1_inst_TXD0   : out   std_logic;
      hps_io_hps_io_emac1_inst_TXD1   : out   std_logic;
      hps_io_hps_io_emac1_inst_TXD2   : out   std_logic;
      hps_io_hps_io_emac1_inst_TXD3   : out   std_logic;
      hps_io_hps_io_emac1_inst_RXD0   : in    std_logic := 'X';
      hps_io_hps_io_emac1_inst_MDIO   : inout std_logic := 'X';
      hps_io_hps_io_emac1_inst_MDC    : out   std_logic;
      hps_io_hps_io_emac1_inst_RX_CTL : in    std_logic := 'X';
      hps_io_hps_io_emac1_inst_TX_CTL : out   std_logic;
      hps_io_hps_io_emac1_inst_RX_CLK : in    std_logic := 'X';
      hps_io_hps_io_emac1_inst_RXD1   : in    std_logic := 'X';
      hps_io_hps_io_emac1_inst_RXD2   : in    std_logic := 'X';
      hps_io_hps_io_emac1_inst_RXD3   : in    std_logic := 'X';
      hps_io_hps_io_sdio_inst_CMD     : inout std_logic := 'X';
      hps_io_hps_io_sdio_inst_D0      : inout std_logic := 'X';
      hps_io_hps_io_sdio_inst_D1      : inout std_logic := 'X';
      hps_io_hps_io_sdio_inst_CLK     : out   std_logic;
      hps_io_hps_io_sdio_inst_D2      : inout std_logic := 'X';
      hps_io_hps_io_sdio_inst_D3      : inout std_logic := 'X';
      hps_io_hps_io_usb1_inst_D0      : inout std_logic := 'X';
      hps_io_hps_io_usb1_inst_D1      : inout std_logic := 'X';
      hps_io_hps_io_usb1_inst_D2      : inout std_logic := 'X';
      hps_io_hps_io_usb1_inst_D3      : inout std_logic := 'X';
      hps_io_hps_io_usb1_inst_D4      : inout std_logic := 'X';
      hps_io_hps_io_usb1_inst_D5      : inout std_logic := 'X';
      hps_io_hps_io_usb1_inst_D6      : inout std_logic := 'X';
      hps_io_hps_io_usb1_inst_D7      : inout std_logic := 'X';
      hps_io_hps_io_usb1_inst_CLK     : in    std_logic := 'X';
      hps_io_hps_io_usb1_inst_STP     : out   std_logic;
      hps_io_hps_io_usb1_inst_DIR     : in    std_logic := 'X';
      hps_io_hps_io_usb1_inst_NXT     : in    std_logic := 'X';
      hps_io_hps_io_uart0_inst_RX     : in    std_logic := 'X';
      hps_io_hps_io_uart0_inst_TX     : out   std_logic;

      instruction_memory_clk_clk       : in  std_logic                     := 'X';  -- clk
      instruction_memory_rst_reset     : in  std_logic                     := 'X';  -- reset
      instruction_memory_rst_reset_req : in  std_logic                     := 'X';  -- reset_req
      instruction_memory_s2_address    : in  std_logic_vector(9 downto 0)  := (others => 'X');  -- address
      instruction_memory_s2_chipselect : in  std_logic                     := 'X';  -- chipselect
      instruction_memory_s2_clken      : in  std_logic                     := 'X';  -- clken
      instruction_memory_s2_write      : in  std_logic                     := 'X';  -- write
      instruction_memory_s2_readdata   : out std_logic_vector(31 downto 0);  -- readdata
      instruction_memory_s2_writedata  : in  std_logic_vector(31 downto 0) := (others => 'X');  -- writedata
      instruction_memory_s2_byteenable : in  std_logic_vector(3 downto 0)  := (others => 'X');  -- byteenable

      data_memory_clk_clk       : in  std_logic                     := 'X';  -- clk
      data_memory_rst_reset     : in  std_logic                     := 'X';  -- reset
      data_memory_rst_reset_req : in  std_logic                     := 'X';  -- reset_req
      data_memory_s2_address    : in  std_logic_vector(9 downto 0)  := (others => 'X');  -- address
      data_memory_s2_chipselect : in  std_logic                     := 'X';  -- chipselect
      data_memory_s2_clken      : in  std_logic                     := 'X';  -- clken
      data_memory_s2_write      : in  std_logic                     := 'X';  -- write
      data_memory_s2_readdata   : out std_logic_vector(31 downto 0);  -- readdata
      data_memory_s2_writedata  : in  std_logic_vector(31 downto 0) := (others => 'X');  -- writedata
      data_memory_s2_byteenable : in  std_logic_vector(3 downto 0)  := (others => 'X');  -- byteenable

      mips_status_export : in  std_logic_vector(31 downto 0) := (others => 'X');  -- export
      pio_leds_export    : out std_logic_vector(31 downto 0)  -- export
      );
  end component soc_mips;

begin

  u0 : component soc_mips
    port map (
      -- Clock and Resets 
      clk_clk       => CLOCK_50,
      -- reset_reset_n           => KEY(0),
      reset_reset_n => '1',

      hps_0_h2f_reset_reset_n => open,

      -- MPU Events 
      hps_0_h2f_mpu_events_eventi     => '0',
      hps_0_h2f_mpu_events_evento     => open,
      hps_0_h2f_mpu_events_standbywfe => open,
      hps_0_h2f_mpu_events_standbywfi => open,

      -- HPS DDR3 Memory 
      memory_mem_a       => HPS_DDR3_ADDR,
      memory_mem_ba      => HPS_DDR3_BA,
      memory_mem_ck      => HPS_DDR3_CK_P,
      memory_mem_ck_n    => HPS_DDR3_CK_N,
      memory_mem_cke     => HPS_DDR3_CKE,
      memory_mem_cs_n    => HPS_DDR3_CS_N,
      memory_mem_ras_n   => HPS_DDR3_RAS_N,
      memory_mem_cas_n   => HPS_DDR3_CAS_N,
      memory_mem_we_n    => HPS_DDR3_WE_N,
      memory_mem_reset_n => HPS_DDR3_RESET_N,
      memory_mem_dq      => HPS_DDR3_DQ,
      memory_mem_dqs     => HPS_DDR3_DQS_P,
      memory_mem_dqs_n   => HPS_DDR3_DQS_N,
      memory_mem_odt     => HPS_DDR3_ODT,
      memory_mem_dm      => HPS_DDR3_DM,
      memory_oct_rzqin   => HPS_DDR3_RZQ,

      -- HPS Ethernet (EMAC1) 
      hps_io_hps_io_emac1_inst_TX_CLK => HPS_ENET_GTX_CLK,
      hps_io_hps_io_emac1_inst_TXD0   => HPS_ENET_TX_DATA(0),
      hps_io_hps_io_emac1_inst_TXD1   => HPS_ENET_TX_DATA(1),
      hps_io_hps_io_emac1_inst_TXD2   => HPS_ENET_TX_DATA(2),
      hps_io_hps_io_emac1_inst_TXD3   => HPS_ENET_TX_DATA(3),
      hps_io_hps_io_emac1_inst_RXD0   => HPS_ENET_RX_DATA(0),
      hps_io_hps_io_emac1_inst_MDIO   => HPS_ENET_MDIO,
      hps_io_hps_io_emac1_inst_MDC    => HPS_ENET_MDC,
      hps_io_hps_io_emac1_inst_RX_CTL => HPS_ENET_RX_DV,
      hps_io_hps_io_emac1_inst_TX_CTL => HPS_ENET_TX_EN,
      hps_io_hps_io_emac1_inst_RX_CLK => HPS_ENET_RX_CLK,
      hps_io_hps_io_emac1_inst_RXD1   => HPS_ENET_RX_DATA(1),
      hps_io_hps_io_emac1_inst_RXD2   => HPS_ENET_RX_DATA(2),
      hps_io_hps_io_emac1_inst_RXD3   => HPS_ENET_RX_DATA(3),

      -- HPS SD Card 
      hps_io_hps_io_sdio_inst_CMD => HPS_SD_CMD,
      hps_io_hps_io_sdio_inst_CLK => HPS_SD_CLK,
      hps_io_hps_io_sdio_inst_D0  => HPS_SD_DATA(0),
      hps_io_hps_io_sdio_inst_D1  => HPS_SD_DATA(1),
      hps_io_hps_io_sdio_inst_D2  => HPS_SD_DATA(2),
      hps_io_hps_io_sdio_inst_D3  => HPS_SD_DATA(3),

      -- HPS USB 
      hps_io_hps_io_usb1_inst_D0  => HPS_USB_DATA(0),
      hps_io_hps_io_usb1_inst_D1  => HPS_USB_DATA(1),
      hps_io_hps_io_usb1_inst_D2  => HPS_USB_DATA(2),
      hps_io_hps_io_usb1_inst_D3  => HPS_USB_DATA(3),
      hps_io_hps_io_usb1_inst_D4  => HPS_USB_DATA(4),
      hps_io_hps_io_usb1_inst_D5  => HPS_USB_DATA(5),
      hps_io_hps_io_usb1_inst_D6  => HPS_USB_DATA(6),
      hps_io_hps_io_usb1_inst_D7  => HPS_USB_DATA(7),
      hps_io_hps_io_usb1_inst_CLK => HPS_USB_CLKOUT,
      hps_io_hps_io_usb1_inst_STP => HPS_USB_STP,
      hps_io_hps_io_usb1_inst_DIR => HPS_USB_DIR,
      hps_io_hps_io_usb1_inst_NXT => HPS_USB_NXT,

      -- HPS UART 
      hps_io_hps_io_uart0_inst_RX => HPS_UART_RX,
      hps_io_hps_io_uart0_inst_TX => HPS_UART_TX,

      -- Instruction Memory Wiring
      instruction_memory_clk_clk       => CLOCK_50,
      instruction_memory_rst_reset     => not KEY(0),
      instruction_memory_rst_reset_req => '0',  -- Tied to 0
      -- instruction_memory_s2_address    => imem_address,
      instruction_memory_s2_address    => current_pc(11 downto 2),
      instruction_memory_s2_chipselect => '1', instruction_memory_s2_clken => '1',
      instruction_memory_s2_write      => '0',
      instruction_memory_s2_readdata   => imem_readdata,
      instruction_memory_s2_writedata  => (others => '0'),
      instruction_memory_s2_byteenable => "1111",

      -- Data Memory Wiring
      data_memory_clk_clk       => CLOCK_50,
      data_memory_rst_reset     => not KEY(0),
      data_memory_rst_reset_req => '0',  -- Tied to 0
      data_memory_s2_address    => dmem_address(11 downto 2),
      data_memory_s2_chipselect => '1',
      data_memory_s2_clken      => '1',
      data_memory_s2_write      => dmem_write,
      data_memory_s2_readdata   => dmem_readdata,
      data_memory_s2_writedata  => r2_data_o,
      data_memory_s2_byteenable => dmem_byteen,

      -- FPGA Custom Fabric Bridges 
      pio_leds_export    => hps_to_fpga_signal,
      mips_status_export => current_pc);

  pc_mips : pc
    port map(
      clk        => CLOCK_50,
      reset      => SW(0),
      en         => pc_en,
      next_pc    => next_pc,
      current_pc => current_pc
      );
  register_mips : regist
    port map(
      clk       => CLOCK_50,
      r1_addr_i => imem_readdata(25 downto 21),
      r2_addr_i => imem_readdata(20 downto 16),
      w_addr_i  => w_addr_i,
      w_data_i  => w_data_i,
      w_en_i    => reg_write,
      r1_data_o => r1_data_o(31 downto 0),
      r2_data_o => r2_data_o(31 downto 0)
      );
  main_control : main_ctrl
    port map(
      op_code   => imem_readdata(31 downto 26),
      reg_dst   => reg_dst,
      alu_src   => alu_src,
      mem_2_reg => mem_2_reg,
      -- reg_write => reg_write,
      reg_write => ctrl_reg_write,
      mem_read  => mem_read,
      -- mem_write => dmem_byteen,
      mem_write => ctrl_mem_write,
      branch    => branch,
      alu_op    => alu_op(1 downto 0)
      );

  mux_register_inst : mux_register
    port map(
      address_0 => imem_readdata(20 downto 16),
      address_1 => imem_readdata(15 downto 11),
      sel       => reg_dst,
      output    => w_addr_i
      );

  alu_controller : alu_ctrl
    port map(
      alu_op      => alu_op(1 downto 0),
      func_code   => imem_readdata(5 downto 0),
      alu_control => alu_control_signal(3 downto 0)
      );

  sign_32_bit : sign_extender
    port map(
      petit    => imem_readdata(15 downto 0),
      extended => jmp_pc(31 downto 0)
      );

  mux_alu_mips : mux_alu
    port map(
      data_from_register      => r2_data_o(31 downto 0),
      data_from_sign_extender => jmp_pc(31 downto 0),
      alu_src                 => alu_src,
      output                  => data_from_mux_to_alu(31 downto 0)
      );

  alu_mips : alu
    port map(
      in_a        => r1_data_o(31 downto 0),
      in_b        => data_from_mux_to_alu(31 downto 0),
      alu_control => alu_control_signal(3 downto 0),
      zero        => alu_zero,
      alu_out     => dmem_address
      );

  mux_out_data : mux_32
    port map(
      input_0 => dmem_address,
      input_1 => dmem_readdata,
      sel     => mem_2_reg,
      output  => w_data_i
      );

  left_shifter : shift_2
    port map(
      input   => jmp_pc,
      shifted => shifted_2
      );

  adder_branch_target : adder_32
    port map(
      input_0 => normal_next_pc,
      input_1 => shifted_2,
      result  => jmp_added
      );
  adder_pc : adder_32
    port map(
      input_0 => current_pc,
      input_1 => pc_offset,
      result  => normal_next_pc
      );
  mux_jmp_pc : mux_32
    port map(
      input_0 => normal_next_pc,
      input_1 => jmp_added,
      sel     => pc_src,
      output  => next_pc
      );

  pc_src <= alu_zero and branch;

  mips_switcher : switcher
    port map(
      clk            => CLOCK_50,
      reset          => SW(0),
      button         => KEY(0),
      manual_en      => SW(9),
      ctrl_reg_write => ctrl_reg_write,
      ctrl_mem_write => ctrl_mem_write,
      pc_en          => pc_en,
      reg_write      => reg_write,
      dmem_write     => dmem_write,
      dmem_byteen    => dmem_byteen
      );

  LEDR(0) <= dmem_byteen(0);

  HEX0 <=bits_2_display7(imem_readdata(3 downto 0));
  HEX1 <=bits_2_display7(imem_readdata(7 downto 4));
  HEX2 <=bits_2_display7(imem_readdata(11 downto 8));
  HEX3 <=bits_2_display7(imem_readdata(15 downto 12));
  HEX4 <= bits_2_display7(current_pc(3 downto 0));
  HEX5 <= bits_2_display7(current_pc(7 downto 4));

  -- HEX0 <= bits_2_display7(r2_data_o(3 downto 0));
  -- HEX1 <= bits_2_display7(r2_data_o(7 downto 4));
  -- HEX2 <= bits_2_display7(r2_data_o(11 downto 8));
  -- HEX3 <= bits_2_display7(r2_data_o(15 downto 12));
  -- HEX4 <= bits_2_display7(r2_data_o(19 downto 16));
  -- HEX5 <= bits_2_display7(r2_data_o(23 downto 20));

end rtl;
